# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitprofile < Formula
  desc "Manage multiple git identities and SSH keys per directory."
  homepage "https://github.com/meanii/gitprofile"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meanii/gitprofile/releases/download/v0.3.0/gitprofile_0.3.0_darwin_amd64.tar.gz"
      sha256 "531cefb9742540bda50dc3e386bdae5e16d082df330e9d2c3c0a181dd85ff453"

      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meanii/gitprofile/releases/download/v0.3.0/gitprofile_0.3.0_darwin_arm64.tar.gz"
      sha256 "afd28f19906357505df83fc1fca93fcaad6f92a6d7f6511bd21e213842bc4f1a"

      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meanii/gitprofile/releases/download/v0.3.0/gitprofile_0.3.0_linux_amd64.tar.gz"
      sha256 "20edcae58d3acb568661d761238ad3ab81dd23f0f6a64037a7daa493f222495f"
      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meanii/gitprofile/releases/download/v0.3.0/gitprofile_0.3.0_linux_arm64.tar.gz"
      sha256 "b43ba06a67a5fe893a640dd6ce924b95c89a54c2202cc5e88a9365b2b619205b"
      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
  end

  test do
    system "#{bin}/gitprofile", "--version"
  end
end
