# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitprofile < Formula
  desc "Manage multiple git identities and SSH keys per directory."
  homepage "https://github.com/meanii/gitprofile"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meanii/gitprofile/releases/download/v0.1.0/gitprofile_0.1.0_darwin_amd64.tar.gz"
      sha256 "b72ebd04d1f8231424c2bb73e342c625a3564f74ace1360d57c48262eb4a0472"

      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meanii/gitprofile/releases/download/v0.1.0/gitprofile_0.1.0_darwin_arm64.tar.gz"
      sha256 "dc9a5389d2dbe7f2dec4aba8b420c8f3accfff5db23829fd54e3483cea459768"

      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meanii/gitprofile/releases/download/v0.1.0/gitprofile_0.1.0_linux_amd64.tar.gz"
      sha256 "3de1bb2a9e9459c5639b74f4244c77067fc0da5f4e9053da307609e0224bab99"
      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meanii/gitprofile/releases/download/v0.1.0/gitprofile_0.1.0_linux_arm64.tar.gz"
      sha256 "b8e5a15b05251ad93b250e19b03282cbd36584c28d619ab6cf5b17cedcc449cf"
      define_method(:install) do
        bin.install "gitprofile"
        bash_completion.install "completions/gitprofile.bash" => "gitprofile"
        zsh_completion.install  "completions/gitprofile.zsh"  => "_gitprofile"
        fish_completion.install "completions/gitprofile.fish"
      end
    end
  end

  test do
    system "#{bin}/gitprofile", "--version"
  end
end
